### ISSUE TITLE
using at ubuntu

### ISSUE THREAD

**Issue by saravutpipat** [SomeGuyCalledBru/same-old-boring-crypto-sniper#1]
**Make sure that you read the Readme before creating a report.**

**Describe the bug**
some js , css file return 304

**To Reproduce**
i just put file there , edit config , run the main

**Expected behavior**
some js , css file return 304 , and the index blank

**Screenshots**
https://prnt.sc/26o3i0t

**OS, Python version and browser version**
ubuntu 20.04 , python 3.8.10

if can i know your telegram , will be better

**Comment by SomeGuyCalledBru** [comment]
This was only tested on Windows, so I'm not very surprised that you're running into all sorts of unexpected things. That being said, I'd be happy to try and fix whatever is going down. Could you attach a screenshot of your DevTools console logs?

**Comment by saravutpipat** [comment]
How i can see it ?

**Comment by bru53001** [comment]
CTRL+Shift+I, click the Console option.

**Comment by saravutpipat** [comment]
Thanks, I'll do it in few hours

Currently outside home

But if im remember its all false at there


Btw it was working before

**Comment by SomeGuyCalledBru** [comment]
Were you able to test things out? I have a new version ready, waiting for this issue to be resolved to get it out.

**Comment by saravutpipat** [comment]
> Were you able to test things out? I have a new version ready, waiting for this issue to be resolved to get it out.
> 
> I currently suspect the cause of this to be linked to the fact that you're accessing the server from an outside source. At the moment, the code of the website allows 2.5 seconds+connectivity check for all HTTP requests to finish. You seem to be exceeding 2.5s in your requests(there are 3 more calls after `/dex`, and that call is already past 2.5sec). So the page tries to render the page while not ready and fails.

it was working if i using at local
but if i want integrated it with private node ( which i need upload to my ubuntu )
the css its dont want to load

**Comment by SomeGuyCalledBru** [comment]
https://github.com/SomeGuyCalledBru/same-old-boring-crypto-sniper/releases/tag/v0.3.0-alpha 

Test this out, the index page should actually load now. I'm not really sure what's causing the base gas issue though-nothing in the code is called a function by that name. It's likely an issue with web3.py rather than this.

**Comment by SomeGuyCalledBru** [comment]
I'm closing this issue for now as this is getting inactive, there's a solution and I've tested with both local-remote, both seem to render the index just fine. If that's not the case with you or you have more questions, feel free to reopen.
